addons:
  apt:
    packages:
      - emacs23-nox
script: make
after_success: ./push.sh
env:
  global:
    - secure: "KmWM62nv1nsKFWE+476wlSgPItSon77GlYouHVgD/LBY1gxF3AwOkordv5BeME4subo46a8YKIroDoRE+Lb6/k0hLMxEvkAuo+ifS0LveV3qagIP97MfCZxVaJaCBMPyPYVJCvGYbEC4MBPsd+0OekIBC3pgCsn+WEoXZdWnVA9gzFUGMp2tVHoa92Sm/VieB6a5FN2HU/wMM6p0i6TwXcOYBsghyCRXXpKBLkugAPjGe3eGuH/ubNWmCEpDm4YVkL88ZseYYjK0wVjRIVlnsm6qZFYrR69SRx5Oa8/d6xUj5Rbh3ICwMh0bcKh32PGimzjMBwSXqqeI1+xAFhQL+3pNR89x8h0ujEp2RxppuoRKg26o74v6fgHzhIUTjejAR3h6CPIbaDcZY1m0R2AomFrXJYdEwc/2ANHFyflbEEw4nPX3fAmqXOliBx938QihidtLNgoy4GeloSUkKEBRkDYxIuTQQ2GRuV0Ikz8cG5pR8xTC17Xn0B66QDMiZGH+E/JSTW22upRdfGYvih7ZK0A8EdhDULSt17ju7xt1bPcr3r0ijUnPmGYx6P02EW1sZb2ULy6HDLRZ+gJXnlfbIzwRNdybqL3WgtzYq4TBTzXr/K+4ivpEcpLhC96bbXWMgHui/HRZ8TDgo/DbvNqHuB3SWTQiyAY1UfhWVMzLBtg="
