addons:
  apt:
    packages:
      - emacs23-nox
script: make
after_success: ./push.sh
secure: "RE536yl1eeJ3f85HF0aON+iZ9ewKmifDu/9RkqiUGGSjLdVwii4TWxv3C9bm3WzwqvT/+2sNYagFc3DqL5GK/vwvKjHhkoEgpb9bK6Tr3/bnuy02gxKjFzHXyIoE4jK/o4GlN4qKdDD4RDMPvaHLSnaywrVO/kgxPul0Reb6DfndZRV/34REj0yju/T1ULTizJHDQZwcGJvgiLbA5Str2HJm/ln5cWfn53tfgbqcBJdSRWbrCoMmWeeQt+QXf4icaMvRX0OkVTTHC3SpizbfKdeeZz2SsAOUYC1UJrxpaJC7cd9jGIcCzbOohrhlSSsFO6NrKNnv9ufXxed8tyQv+VGzdQzYW+ehYQ+E0X0Ul3fsIKgAHZ4qA7g2Dgnai1YYCGlM2Yuwk4v2Q/DSNS0tqgfLnLLnam2yklknEBbtQe3LqxAyfwJgWSDZojRT/nL1EqiuhIWV4NUyX/hFruB66RBgbEJ8K1uKPZWckCPMNF6o1raeL5Bag7lJTCnksfiCecC6GgsipMJAqgFDJhyD3dLKhyB4dzR/4Temy4e2D4rs3Z5wrBTOQNxQVSzdb91wPDpz4qEvxvkaJHc6Ip+/PsZ5UAb4kc+cNI53+pZzc1xgHmav70PFSICP807yaGEzsZlfY5aCLW3sHB2w3yu2AesBQ9j98RHpjAq3Q5KCY9M="