addons:
  apt:
    packages:
      - emacs23-nox
script: make
after_success: ./push.sh
secure: "WRXo/R67g/GKa8DwrR1r56RJP99+Jsg1wjNPvO01ukWvtBGIrEmLyE6YtT+QtrWRlse+ixl5B1d5OtmnNbLD2WtBRKdnvJnVAKFMjJwknpZ6WagqzBJlfJNQ1IwxcGWfIBk+7tCE9OJ9FTtf8c/Wpu+RzlZvkFunILln+IaS7kHjv93DKRmlWr+kAAQoEI6RsDLS1A/CwyU6Q3m8Pe+g9SoPjV4tcuHTOLdnYiSY5f6VZ14Q5EPNSOg/hIJ/Kc5UdZhdYO/2mpBNxJUci8ULhCjgcMPvnzgmh94O+hF8tUBMSET95G7JG7b9+a2ei/BJj6o9RVq+f3sdu31m5tMZBo7FNdnuDZtZG9HZFKa/GxOjPt/EeBMQBEktywkYjARYT5PJlJanSt0hZJ79yrxOE3w/H4vCRiH6ftqsWf9f27p5BfKHCqiIMxJeo+WvMyats/10/X49b6EXx4p5wMBWkG+h2uXqP2BwURTO+53NUQhFvLqw1RpYaVxHvB8l/WcSc/3LLLFg0W4Qr8fU2mstEfw5F1U4pF85MSsTqRWXuyHxULHn3EhRhlrsGp1KftlV5ZTRbwQ9xki9V7ML7j9tcdzrsAI8zH7zQoK1cspJ//0oFHjqkPZCLCTqG2tX8zb942j/9Pl04Gk0CVehKz9Kkb7P9PwveUOwZKdO45D8Hn4="