addons:
  apt:
    packages:
      - emacs23-nox
script: make
after_success: ./push.sh
secure: "aRpROBcp2ir23btst8H0ASmkJjW9GPKgpRltHMo6vOeTa+q8CXV7OdwnZbEVksaFT7xBeJmJv5mI/U0rXqQxIXyrDvUPUfHAn4i5U89FCWLNrQ6+5QwYZFBLfeGTAfMh63s5RPckKjxkGjel6JZ/I0sOk65aN/1HHQa1jPSb2keWm44BO8a4qiKJUbFWfS/nH5FzmUjx/tweWFDOG/IW8kkc+RT7KAewVae06THr7PreOwIXc2/iCJq1AIBID1m1P4cqlHF1FT1WjSO8VNyFXTGKvJvfTNiSUflOXf3dzmx3ZazR/rWgCRvumfzO9VGUKid6wsV2vuwG30Fp/lf/jEESgU0uPrxOmPJ80CK0tZEZqcmGnAvs74OZjaAfEKrTkriWeBsKjmnEnfkK01wbynIGvWwXXlI0CCSqcQl9zXL8vDtabM68X8A1aPAxI/oO0490HvOp9GYraLMGKsiuv+jU01FnjXNcmuEo0Pu9S09Vq1bJ4gXX+tW+8ayvdz0ga9TttGHM45aNv8Q2hc7/ELfyu91X0x2MtKSlFxMaHxgXt87oYqxfNMK37FejfVki8KOaJlORNXH7skPc8+xcUxuhTF+idAgUq67odHJ5+pC0RLwffOtOp7FLwnuaXFUe+/CJy65NXbc3oTTWCSu7Npa9RgQDB4eVeLzfAXpuyXg="